services:
  neo4j:
    image: neo4j:5.20.0-community
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_memory_heap_initial__size=512M
      - NEO4J_server_memory_heap_max__size=2G

    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null -q http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
    
volumes:
  neo4j-data:
  neo4j-logs: